import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as echarts from 'echarts/core';
import {LineChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,LegendComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
echarts.use([LineChart,GridComponent,TooltipComponent,LegendComponent,CanvasRenderer]);
import './style.css';
import {api, exportCsv, STATIC_MODE} from './api';

type Row={code:string;name:string;board:string;close:number;stock_return:number;index_return:number;gap:number;opposite_days:number;rule:string};
type Result={batch_id:string;source:string;updated_at:string;base_date:string;start_date:string;end_date:string;window:number;index_return:number;candidate_count:number;valid_count:number;total_matches:number;incomplete:boolean;exclusion_counts:Record<string,number>;excluded:{code:string;name:string;reason:string}[];results:Row[]};
type Job={id:string;state:string;stage:string;done:number;total:number;success:number;failed:number;message:string;elapsed_seconds?:number};
type Status={batch:{id:string;end_date:string;created:string}|null;job:Job|null;stock_count:number;downloaded:number;errors:number;first_date:string|null};
type Params={end:string;window:number;mode:string;direction:string;board:string;stock_min:number;index_min:number;search:string;sort:string;descending:boolean};
type Point={date:string;stock:number;index:number;stock_day:number|null;index_day:number|null;opposite:boolean;close:number};
type Detail=Row&{series:Point[];base_date:string;end_date:string;window:number};
const defaults:Params={end:'',window:3,mode:'strict',direction:'down',board:'all',stock_min:0,index_min:0,search:'',sort:'gap',descending:true};
const pct=(n:number|undefined)=>n==null?'—':`${n>0?'+':''}${n.toFixed(2)}%`;
const tone=(n:number)=>n>0?'positive':n<0?'negative':'';
const number=(n:number|undefined)=>n==null?'—':n.toLocaleString('zh-CN');
function qs(p:Params,batch?:string){const x=new URLSearchParams(); Object.entries(p).forEach(([k,v])=>{if(v!=='')x.set(k,String(v))});if(batch)x.set('batch_id',batch);return x.toString()}

function Chart({series}:{series:Point[]}){const el=useRef<HTMLDivElement>(null);useEffect(()=>{if(!el.current)return;const chart=echarts.init(el.current);chart.setOption({color:['#2365df','#ea9a37'],animation:false,legend:{bottom:0,icon:'roundRect'},tooltip:{trigger:'axis',valueFormatter:(v:number)=>pct(v)},grid:{left:48,right:18,top:20,bottom:60},xAxis:{type:'category',data:series.map(s=>s.date.slice(5)),axisLine:{lineStyle:{color:'#ccd5e3'}}},yAxis:{type:'value',axisLabel:{formatter:'{value}%'},splitLine:{lineStyle:{color:'#edf1f7'}}},series:[{name:'股票（后复权）',type:'line',symbolSize:7,data:series.map(s=>s.stock),lineStyle:{width:3}},{name:'上证综指',type:'line',symbolSize:6,data:series.map(s=>s.index),lineStyle:{width:2,type:'dashed'}}]});const obs=new ResizeObserver(()=>chart.resize());obs.observe(el.current);return()=>{obs.disconnect();chart.dispose()}},[series]);return <div className="chart" ref={el} role="img" aria-label="股票与上证指数累计涨跌幅对比，下方提供每日数据表"/>}

function App(){
 const [params,setParams]=useState<Params>(defaults),[applied,setApplied]=useState<Params>(defaults);
 const [status,setStatus]=useState<Status|null>(null),[result,setResult]=useState<Result|null>(null);
 const [error,setError]=useState(''),[connection,setConnection]=useState(''),[busy,setBusy]=useState(false);
 const [detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(''),[selected,setSelected]=useState<Row|null>(null);
 const [showExcluded,setShowExcluded]=useState(false),[page,setPage]=useState(1);
 const loaded=useRef(false),requestId=useRef(0),detailId=useRef(0),closeRef=useRef<HTMLButtonElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 async function run(p:Params,batch?:string){const id=++requestId.current;setBusy(true);setError('');setSelected(null);detailId.current++;try{const data=await api<Result>('/api/screen?'+qs(p,batch));if(id!==requestId.current)return;setResult(data);setApplied(p);setPage(1)}catch(e){if(id===requestId.current){setError((e as Error).message);setResult(null)}}finally{if(id===requestId.current)setBusy(false)}}
 useEffect(()=>{let active=true;async function poll(){try{const s=await api<Status>('/api/status');if(!active)return;setStatus(s);setConnection('');if(s.batch&&!loaded.current){loaded.current=true;void run(defaults,s.batch.id)}}catch{if(active)setConnection(STATIC_MODE?'无法读取已发布行情，请稍后刷新重试。':'无法连接本机服务，请检查启动窗口是否仍在运行。')}}void poll();const timer=setInterval(poll,STATIC_MODE?60000:3000);return()=>{active=false;clearInterval(timer)}},[]);
 const close=()=>{detailId.current++;setSelected(null);setDetail(null);previousFocus.current?.focus()};
 useEffect(()=>{if(!selected)return;closeRef.current?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.drawer button,.drawer a'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener)},[selected]);
 function update<K extends keyof Params>(key:K,value:Params[K]){setParams(p=>({...p,[key]:value}))}
 async function refresh(){try{const job=await api<Job>('/api/refresh',{method:'POST'});setStatus(s=>s?{...s,job}:null);setConnection('')}catch(e){setConnection((e as Error).message)}}
 async function open(row:Row){if(!result)return;previousFocus.current=document.activeElement as HTMLElement;setSelected(row);setDetail(null);setDetailError('');const id=++detailId.current;try{const d=await api<Detail>(`/api/stocks/${row.code}/comparison?batch_id=${result.batch_id}&end=${result.end_date}&window=${result.window}`);if(id===detailId.current)setDetail(d)}catch(e){if(id===detailId.current)setDetailError((e as Error).message)}}
 function sort(key:string){const next={...applied,sort:key,descending:applied.sort===key?!applied.descending:true};setParams(p=>({...p,sort:next.sort,descending:next.descending}));void run(next,result?.batch_id)}
 const running=status?.job?.state==='running', rows=result?.results.slice((page-1)*30,page*30)||[];
 const pages=Math.max(1,Math.ceil((result?.results.length||0)/30));
 const dirty=JSON.stringify(params)!==JSON.stringify(applied);
 return <><header className="topbar"><div className="brand"><span className="brand-icon">↗<i>↘</i></span><span>沪市背离<span className="brand-light">观察台</span></span><span className="local">{STATIC_MODE?"在线版":"本机版"}</span></div><div className="topnote">上证综指 · 沪市 A 股<span className="separator">|</span>收盘后更新</div></header>
 <main><div className="heading"><div><div className="eyebrow">MARKET DIVERGENCE / 市场观察</div><h1>发现与大盘反向的股票</h1><p>以同一段交易时间，对照个股与上证综指的价格走势。</p></div><button className="secondary update" disabled={running} onClick={refresh}><span className={running?'spin':''}>⟳</span> {running?'正在更新行情':STATIC_MODE?'刷新已发布行情':'更新行情'}</button></div>
 {(connection||error)&&<div className="notice danger" role="alert">{connection||error}</div>}
 {status?.job&&<div className={'job '+(status.job.state==='failed'?'job-failed':'')} aria-live="polite"><div><strong>{status.job.stage}</strong><span>{status.job.message}</span></div><small>{status.job.total>0?`${status.job.done} / ${status.job.total} · 成功 ${status.job.success}`:''}{status.job.elapsed_seconds?` · 已用 ${Math.round(status.job.elapsed_seconds)} 秒`:''}</small>{running&&<progress max={status.job.total||100} value={status.job.total?status.job.done:undefined}/>}</div>}
 {result&&status?.batch&&status.batch.id!==result.batch_id&&<div className="notice">新行情批次已就绪。<button onClick={()=>run(params,status.batch!.id)}>使用新批次筛选</button></div>}
 <form className="filter-card" onSubmit={e=>{e.preventDefault();void run(params,status?.batch?.id)}}><div className="card-title"><h2>筛选条件</h2><span>基准指数 <b>上证综指 000001</b></span></div>
 <div className="filters"><label>截止日期<input type="date" value={params.end} onChange={e=>update('end',e.target.value)}/><small>留空使用最新可用收盘日</small></label>
 <label>观察窗口<div className="window-input"><input aria-label="交易日数量" type="number" min="2" max="60" required value={params.window} onChange={e=>update('window',Number(e.target.value))}/><span>交易日</span></div><div className="presets">{[3,5,10,20].map(n=><button key={n} type="button" className={params.window===n?'active':''} onClick={()=>update('window',n)}>{n} 日</button>)}</div></label>
 <label>背离判定<select value={params.mode} onChange={e=>update('mode',e.target.value)}><option value="strict">每日严格背离</option><option value="cumulative">区间累计背离</option></select><small>{params.mode==='strict'?'每天均满足同一个反向条件':'仅比较区间首尾累计涨跌'}</small></label>
 <label>背离方向<select value={params.direction} onChange={e=>update('direction',e.target.value)}><option value="down">指数上涨 · 股票下跌</option><option value="up">指数下跌 · 股票上涨</option><option value="both">两个方向</option></select></label></div>
 <div className="filter-bottom"><label>股票范围<select value={params.board} onChange={e=>update('board',e.target.value)}><option value="all">全部沪市 A 股</option><option value="main">主板</option><option value="star">科创板</option></select></label><label>股票最小区间涨跌幅（绝对值 %）<input type="number" step="0.01" min="0" max="1000" required value={params.stock_min} onChange={e=>update('stock_min',Number(e.target.value))}/></label><label>指数最小区间涨跌幅（绝对值 %）<input type="number" step="0.01" min="0" max="1000" required value={params.index_min} onChange={e=>update('index_min',Number(e.target.value))}/></label><button className="primary" disabled={busy||!status?.batch}>{busy?'计算中…':'开始筛选'} <span>→</span></button></div>
 <div className="filter-foot"><span>ⓘ {params.window} 个交易日使用 {params.window+1} 个收盘价 · 股票按后复权价格计算</span>{dirty&&result&&<span>条件已更改，点击“开始筛选”应用</span>}</div></form>
 <section className="metrics" aria-label="结果概览"><article><span>符合条件的股票</span><strong>{number(result?.total_matches)}<small>只</small></strong><p>{result?`${result.window} 个交易日 · ${applied.mode==='strict'?'每日严格背离':'区间累计背离'}`:'完成行情更新后开始筛选'}</p></article><article><span>上证综指区间涨跌</span><strong className={tone(result?.index_return||0)}>{pct(result?.index_return)}</strong><p>{result?`${result.start_date} 至 ${result.end_date}`:'统一交易日，同一收盘时点'}</p></article><article><span>有效分析覆盖</span><strong>{number(result?.valid_count)}<small>/ {number(result?.candidate_count)}</small></strong><p>{result?.incomplete?'部分数据不足，请查看排除明细':'排除停牌、缺失和价格异常'}</p></article><article><span>数据截至</span><strong className="date-value">{result?.end_date||status?.batch?.end_date||'尚未采集'}</strong><p>{result?`基准日 ${result.base_date}`:'仅使用完整交易日收盘数据'}</p></article></section>
 {result?.incomplete&&<div className="notice"><span>数据不完整：{Object.entries(result.exclusion_counts).map(([k,v])=>`${k} ${v} 只`).join('；')}。</span><button onClick={()=>setShowExcluded(!showExcluded)}>{showExcluded?'收起明细':'查看排除明细'}</button></div>}
 {showExcluded&&result&&<div className="excluded"><table><thead><tr><th>代码</th><th>名称</th><th>排除原因</th></tr></thead><tbody>{result.excluded.map(x=><tr key={x.code}><td>{x.code}</td><td>{x.name}</td><td>{x.reason}</td></tr>)}</tbody></table></div>}
 <section className="results-card"><div className="results-title"><div><h2>背离股票</h2><span>{({gap:'涨跌幅差',stock_return:'股票涨跌',index_return:'指数涨跌',code:'股票代码',close:'收盘价',opposite_days:'反向天数'} as Record<string,string>)[applied.sort]}{applied.descending?'降序':'升序'} · 差值单位：百分点</span></div><div className="table-actions"><input aria-label="搜索股票代码或名称" placeholder="搜索代码 / 名称" value={params.search} onChange={e=>{update('search',e.target.value);if(result){const p={...applied,search:e.target.value};void run(p,result.batch_id)}}}/><a onClick={e=>{if(STATIC_MODE){e.preventDefault();if(result)void exportCsv("/api/export?"+qs(applied,result.batch_id)).catch(e=>setError(e.message))}}} className={'export '+(!result?'disabled':'')} href={result?'/api/export?'+qs(applied,result.batch_id):undefined}>↓ 导出 CSV</a></div></div>
 <div className="table-wrap"><table><thead><tr><th>股票 / 代码</th><th>板块</th><th><button onClick={()=>sort('close')}>收盘价 ↕</button></th><th><button onClick={()=>sort('stock_return')}>股票涨跌 ↕</button></th><th>指数涨跌</th><th><button onClick={()=>sort('gap')}>涨跌幅差 ↕</button></th><th><button onClick={()=>sort('opposite_days')}>反向天数 ↕</button></th><th>判定</th></tr></thead><tbody>{rows.map(r=><tr key={r.code}><td><button className="stock-link" onClick={()=>open(r)}><b>{r.name}</b><small>{r.code}.SH</small></button></td><td><span className={'board '+(r.board==='star'?'star':'')}>{r.board==='main'?'主板':'科创板'}</span></td><td>{r.close.toFixed(2)}</td><td className={tone(r.stock_return)}>{pct(r.stock_return)}</td><td className={tone(r.index_return)}>{pct(r.index_return)}</td><td className="gap">{r.gap.toFixed(2)}</td><td>{r.opposite_days} <span className="muted">/ {result!.window}</span></td><td><span className="rule">{r.rule}</span></td></tr>)}</tbody></table></div>
 {!rows.length&&<div className="empty"><div className="empty-icon">⌁</div><h3>{busy?'正在计算筛选结果':error?'暂时无法计算':!status?.batch?'等待第一批真实行情':result?'当前条件下无符合股票':'准备开始筛选'}</h3><p>{!status?.batch?'点击“更新行情”获取沪市 A 股和上证综指收盘数据。':result?'可切换区间累计背离、调整方向或延长观察窗口。':'完成数据更新后，即可查看股票与指数的背离情况。'}</p>{!status?.batch&&<small>首次采集需要逐只下载，耗时取决于免费接口响应。</small>}</div>}
 <div className="table-footer"><span>{result?`显示 ${result.results.length} 只 · ${result.incomplete?'数据不完整':'窗口数据完整'}`:'真实行情 · 不填充模拟结果'}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>下一页</button></div></div></section>
 <footer><p>当前沪市股票清单 · 历史查询不包含完整退市样本 · 背离描述已发生的走势，不代表未来收益</p><p>{result?`${result.source} · 更新于 ${new Date(result.updated_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}（北京时间）`:'免费公开行情经 AKShare 获取'}</p></footer></main>
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div className="drawer-head"><div><span className="eyebrow">股票详情 / {selected.code}.SH</span><h2 id="detail-title">{selected.name}</h2></div><button ref={closeRef} onClick={close} aria-label="关闭股票详情">✕</button></div>{detailError?<div className="notice danger">{detailError}</div>:!detail?<p>正在读取对照数据…</p>:<><div className="detail-stats"><div>股票区间涨跌<strong className={tone(detail.stock_return)}>{pct(detail.stock_return)}</strong></div><div>上证综指<strong className={tone(detail.index_return)}>{pct(detail.index_return)}</strong></div><div>差值<strong>{detail.gap.toFixed(2)}<small> 个百分点</small></strong></div></div><h3>累计涨跌幅对照</h3><p className="muted">{detail.base_date} 为基准日（0%），使用同一纵轴</p><Chart series={detail.series}/><div className="explanation">指数区间{detail.index_return>=0?'上涨':'下跌'} {Math.abs(detail.index_return).toFixed(2)}%，该股{detail.stock_return>=0?'上涨':'下跌'} {Math.abs(detail.stock_return).toFixed(2)}%，相差 {detail.gap.toFixed(2)} 个百分点。{detail.window} 个交易日中有 {detail.opposite_days} 天涨跌方向相反。</div><h3>逐日核对</h3><table className="daily"><thead><tr><th>日期</th><th>股票涨跌</th><th>指数涨跌</th><th>方向</th></tr></thead><tbody>{detail.series.map((s,i)=><tr key={s.date}><td>{s.date}</td><td className={tone(s.stock_day||0)}>{pct(s.stock_day??undefined)}</td><td className={tone(s.index_day||0)}>{pct(s.index_day??undefined)}</td><td>{i===0?'基准日':s.opposite?<span className="rule">反向</span>:'非反向'}</td></tr>)}</tbody></table><p className="muted">后复权价格用于计算涨跌；结果表收盘价为未复权实际价格。</p></>}</aside></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);


